We can not have git fsck enabled because if a broken commit in rails
```
error: object 4cf94979c9f4d6683c9338d694d5eb3106a4e734: badTimezone: invalid author/committer line - bad time zone
fatal: fsck error in packed object
fatal: fetch-pack: invalid index-pack output
```